# Generated by Django 4.2 on 2024-01-26 11:57

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="patronymic",
            field=models.CharField(default="Отчество", max_length=50),
        ),
        migrations.AlterField(
            model_name="user",
            name="first_name",
            field=models.CharField(default="Имя", max_length=50),
        ),
        migrations.AlterField(
            model_name="user",
            name="last_name",
            field=models.CharField(default="Фамилия", max_length=50),
        ),
    ]
