# Generated by Django 4.2 on 2024-02-13 14:42

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=models.FileField(blank=True, max_length=500, null=True, upload_to=""),
        ),
    ]
