# Generated by Django 4.2 on 2024-01-17 17:50

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="rating",
            field=models.SmallIntegerField(default=5),
        ),
    ]
