# Generated by Django 4.2 on 2024-01-26 20:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_user_patronymic_alter_user_first_name_and_more"),
    ]

    operations = [
        migrations.CreateModel(
            name="Schedule",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("time", models.DateTimeField()),
            ],
        ),
        migrations.AddField(
            model_name="user",
            name="times",
            field=models.ManyToManyField(to="users.schedule"),
        ),
    ]
