# Generated by Django 4.2 on 2024-02-13 14:51

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0002_alter_user_photo"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="photo_file",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=models.CharField(blank=True, max_length=500, null=True),
        ),
    ]
