# Generated by Django 4.2 on 2024-01-27 13:48

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_schedule_user_times"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="times",
            field=models.ManyToManyField(blank=True, null=True, to="users.schedule"),
        ),
    ]
