# Generated by Django 4.2 on 2024-02-13 15:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_user_photo_file_alter_user_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=models.CharField(
                blank=True,
                default="https://storage.yandexcloud.net/solevar-bucket/user_images/no-profile.png",
                max_length=500,
                null=True,
            ),
        ),
    ]
