# Generated by Django 4.2 on 2024-02-03 12:11

from django.db import migrations, models
import users.services


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0003_remove_user_unique_series_number"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="passport_number",
            field=models.CharField(
                default="123456",
                max_length=6,
                validators=[users.services.validate_passport_number],
            ),
        ),
        migrations.AlterField(
            model_name="user",
            name="passport_series",
            field=models.CharField(
                default="1122",
                max_length=4,
                validators=[users.services.validate_passport_series],
            ),
        ),
    ]
