# Generated by Django 4.2 on 2024-01-28 10:54

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0004_alter_user_times"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="balance",
            field=models.BigIntegerField(default=0),
        ),
    ]
