# Generated by Django 4.2 on 2024-02-09 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_user_passport_number_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=models.ImageField(
                default="https://storage.yandexcloud.net/solevar-bucket/user_images/no-profile.png",
                upload_to="user_images",
            ),
        ),
    ]
