# Generated by Django 4.2 on 2024-01-30 10:40

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0005_alter_user_balance"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="role",
            field=models.CharField(
                choices=[("coach", "Coach"), ("client", "Client"), ("admin", "Admin")],
                default="client",
                max_length=20,
            ),
        ),
    ]
