# Generated by Django 4.2 on 2024-02-02 19:10

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0006_alter_user_role"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="phonenumberverifysms",
            options={
                "verbose_name": "код подтверждения",
                "verbose_name_plural": "Коды подтверждения",
            },
        ),
        migrations.AlterModelOptions(
            name="schedule",
            options={
                "verbose_name": "время занятия",
                "verbose_name_plural": "Расписание занятий",
            },
        ),
        migrations.AlterModelOptions(
            name="user",
            options={
                "verbose_name": "пользователя",
                "verbose_name_plural": "Клиенты | Тренеры",
            },
        ),
        migrations.AddField(
            model_name="schedule",
            name="is_selected",
            field=models.BooleanField(default=False),
        ),
    ]
