# Generated by Django 4.2 on 2024-02-10 07:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_user_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="photo",
            field=models.ImageField(
                default="https://storage.yandexcloud.net/solevar-bucket/user_images/no-profile.png",
                upload_to="user_images",
            ),
        ),
    ]
