# Generated by Django 4.2 on 2024-02-03 07:16

from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_phonenumberverifysms_options_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="times",
        ),
        migrations.AddField(
            model_name="schedule",
            name="coach",
            field=models.ManyToManyField(to=settings.AUTH_USER_MODEL),
        ),
    ]
