# Generated by Django 4.2 on 2024-01-18 09:49

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0007_alter_user_email"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="username",
        ),
    ]
