# Generated by Django 4.2 on 2024-01-19 11:13

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0008_remove_user_username"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="user",
            name="yookassa_payment_id",
        ),
        migrations.AddField(
            model_name="user",
            name="balance",
            field=models.DecimalField(decimal_places=2, default=0, max_digits=10),
        ),
        migrations.AddField(
            model_name="user",
            name="trainer_type",
            field=models.CharField(default="", max_length=100),
        ),
    ]
