# Generated by Django 4.2 on 2024-02-11 05:24

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0010_audiorecord_user_records_files"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="audiorecord",
            options={
                "verbose_name": "запись звонка",
                "verbose_name_plural": "Записи звонков",
            },
        ),
        migrations.AddField(
            model_name="audiorecord",
            name="name",
            field=models.CharField(default=0, max_length=120),
            preserve_default=False,
        ),
        migrations.AlterField(
            model_name="audiorecord",
            name="record_file",
            field=models.FileField(max_length=500, upload_to=""),
        ),
        migrations.AlterField(
            model_name="user",
            name="records_files",
            field=models.ManyToManyField(default="", to="users.audiorecord"),
        ),
    ]
