# Generated by Django 4.2 on 2024-02-11 17:02

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0012_alter_user_date_of_birth_alter_user_description_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="description",
            field=models.TextField(verbose_name="Мое описание"),
        ),
        migrations.AlterField(
            model_name="user",
            name="records_files",
            field=models.ManyToManyField(default="", to="users.audiorecord"),
        ),
        migrations.AlterField(
            model_name="user",
            name="trainer_type",
            field=models.CharField(default="", max_length=100),
        ),
    ]
