# Generated by Django 4.2 on 2024-02-11 17:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0013_alter_user_description_alter_user_records_files_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="records_files",
            field=models.ManyToManyField(default=[], to="users.audiorecord"),
        ),
    ]
