# Generated by Django 4.2 on 2024-02-11 17:09

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0014_alter_user_records_files"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="date_of_birth",
            field=models.DateField(blank=True, default=""),
        ),
        migrations.AlterField(
            model_name="user",
            name="records_files",
            field=models.ManyToManyField(
                blank=True, default="", to="users.audiorecord"
            ),
        ),
    ]
