# Generated by Django 4.2 on 2024-02-12 07:52

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("users", "0017_alter_user_description"),
    ]

    operations = [
        migrations.AlterField(
            model_name="user",
            name="records_files",
            field=models.ManyToManyField(blank=True, null=True, to="users.audiorecord"),
        ),
    ]
