version: '2'

services:
  mysql:
    image: mysql:latest
    container_name: mysql-solevar
    restart: always
    environment:
      - MYSQL_DATABASE=solevar_prod
      - MYSQL_ROOT_PASSWORD=solevar_pass
    volumes:
      - mysql_data:/var/lib/mysql/

  redis: 
    image: redis:latest
    container_name: redis-solevar
    restart: always
    ports:
      - "6379:6379"

  api:
    build: .
    image: itsoda14/solevar:latest
    command:
      - sh
      - -c
      - |
        dockerize -wait tcp://mysql:3306 -timeout 300s &&
        poetry run python manage.py collectstatic --noinput &&
        poetry run python manage.py migrate &&
        poetry run gunicorn solevar.wsgi:application -b :8000
    env_file:
      - docker-compose.env
    environment:
      - DOCKER_CONTAINER=True
      - VIRTUAL_HOST=onlydev.fun
      - LETSENCRYPT_HOST=onlydev.fun
    ports:
      - "8000:8000" 
    depends_on:
      - mysql
      - redis 
    volumes:
      - .:/itsoda
      - static_volume:/itsoda/static
      - media_volume:/itsoda/media
    container_name: django-api
  nginx:
    build: 
      dockerfile: ./Dockerfile
      context: ./docker/nginx/
    container_name: nginx_cityheroes
    image: nginx_cityheroes
    volumes:
      - static_volume:/itsoda/static
      - media_volume:/itsoda/media
      - certs:/etc/nginx/certs
      - vhost:/etc/nginx/vhost.d
      - html:/usr/share/nginx/html
      - /var/run/docker.sock:/tmp/docker.sock:ro
    depends_on:
      - api
    ports:
      - "80:80"
      - "443:443"
  acme_companion:
    image: nginxproxy/acme-companion:2.2
    container_name: solevar_acme_companion
    volumes_from:
      - nginx
    volumes:
      - /var/run/docker.sock:/var/run/docker.sock:ro
      - acme:/etc/acme.sh

volumes:
  mysql_data: null
  static_volume:
  media_volume:
  certs:
  vhost:
  html:
  acme: