# Generated by Django 4.2 on 2024-02-11 08:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tgbot", "0002_alter_admin_options_news_title"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="userbot",
            options={"verbose_name": "тг-юзер", "verbose_name_plural": "тг-юзеры"},
        ),
        migrations.AlterField(
            model_name="news",
            name="photo",
            field=models.ImageField(blank=True, default=0, upload_to=""),
            preserve_default=False,
        ),
    ]
