# Generated by Django 4.2 on 2024-02-13 09:36

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("tgbot", "0003_alter_userbot_options_alter_news_photo"),
    ]

    operations = [
        migrations.AlterField(
            model_name="news",
            name="photo",
            field=models.ImageField(blank=True, null=True, upload_to=""),
        ),
    ]
