# Generated by Django 4.2 on 2024-01-17 14:33

from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("content", models.TextField()),
                ("limit_of_participants", models.SmallIntegerField()),
                ("start_at", models.DateTimeField(auto_now_add=True)),
                ("duration", models.DurationField()),
            ],
            options={
                "verbose_name": "тренировку",
                "verbose_name_plural": "Тренировки",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
            ],
            options={
                "verbose_name": "тег",
                "verbose_name_plural": "Теги",
            },
        ),
    ]
