# Generated by Django 4.2 on 2024-01-20 12:21

import phonenumber_field.modelfields
from django.db import migrations, models


class Migration(migrations.Migration):
    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Club",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("address", models.CharField(max_length=256)),
                (
                    "club_phone",
                    phonenumber_field.modelfields.PhoneNumberField(
                        max_length=128, region=None
                    ),
                ),
                ("club_email", models.EmailField(max_length=254)),
            ],
            options={
                "verbose_name": "клуб",
                "verbose_name_plural": "Клубы",
            },
        ),
        migrations.CreateModel(
            name="Event",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("title", models.CharField(max_length=128)),
                ("content", models.TextField()),
                ("limit_of_participants", models.SmallIntegerField()),
                ("start_at", models.DateTimeField(auto_now_add=True)),
                ("duration", models.DurationField()),
            ],
            options={
                "verbose_name": "тренировку",
                "verbose_name_plural": "Тренировки",
            },
        ),
        migrations.CreateModel(
            name="IndividualEvent",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("start_datetime", models.DateTimeField()),
                ("end_datetime", models.DateTimeField()),
                ("description", models.TextField()),
                ("duration_minutes", models.PositiveIntegerField()),
            ],
            options={
                "verbose_name": "индивидуальную тренировку",
                "verbose_name_plural": "Индивидуальные тренировки",
            },
        ),
        migrations.CreateModel(
            name="Subscription",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("number", models.UUIDField(unique=True)),
                ("start_date", models.DateTimeField(auto_now_add=True)),
                ("end_date", models.DateTimeField()),
                ("price", models.DecimalField(decimal_places=2, max_digits=10)),
            ],
            options={
                "verbose_name": "aбонемент",
                "verbose_name_plural": "абонементы",
            },
        ),
        migrations.CreateModel(
            name="Tag",
            fields=[
                (
                    "id",
                    models.BigAutoField(
                        auto_created=True,
                        primary_key=True,
                        serialize=False,
                        verbose_name="ID",
                    ),
                ),
                ("name", models.CharField(max_length=64)),
            ],
            options={
                "verbose_name": "тег",
                "verbose_name_plural": "Теги",
            },
        ),
    ]
