# Generated by Django 4.2 on 2024-01-24 12:07

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gym_management", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="end_date",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
