# Generated by Django 4.2 on 2024-01-20 15:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gym_management", "0002_initial"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="duration",
            field=models.IntegerField(),
        ),
    ]
