# Generated by Django 4.2 on 2024-01-25 18:12

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gym_management", "0003_alter_subscription_end_date"),
    ]

    operations = [
        migrations.AddField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "Waiting"),
                    ("canceled", "Canceled"),
                    ("passed", "Passed"),
                ],
                default="waiting",
                max_length=20,
            ),
        ),
    ]
