# Generated by Django 4.2 on 2024-02-06 10:16

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gym_management", "0003_alter_subscription_price_delete_club"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="individualevent",
            options={
                "verbose_name": "персональную тренировку",
                "verbose_name_plural": "Персональные тренировки",
            },
        ),
        migrations.AlterField(
            model_name="individualevent",
            name="duration",
            field=models.PositiveIntegerField(default=60),
        ),
    ]
