# Generated by Django 4.2 on 2024-02-06 13:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gym_management", "0004_alter_individualevent_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="club",
            field=models.CharField(default="Рекорд фитнес ЭКО", max_length=150),
        ),
    ]
