# Generated by Django 4.2 on 2024-02-06 14:11

import django.db.models.deletion
from django.conf import settings
from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("gym_management", "0005_alter_event_club"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="created_by",
            field=models.ForeignKey(
                blank=True,
                on_delete=django.db.models.deletion.CASCADE,
                to=settings.AUTH_USER_MODEL,
            ),
        ),
        migrations.AlterField(
            model_name="event",
            name="participants",
            field=models.ManyToManyField(
                blank=True,
                related_name="participants_event",
                to=settings.AUTH_USER_MODEL,
            ),
        ),
    ]
