# Generated by Django 4.2 on 2024-01-20 16:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gym_management", "0005_alter_event_duration_and_more"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="individualevent",
            name="duration_minutes",
        ),
        migrations.AddField(
            model_name="individualevent",
            name="duration",
            field=models.PositiveIntegerField(default=0),
        ),
        migrations.AlterField(
            model_name="event",
            name="duration",
            field=models.PositiveIntegerField(default=0),
        ),
    ]
