# Generated by Django 4.2 on 2024-01-21 12:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gym_management", "0006_remove_individualevent_duration_minutes_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="subscription",
            name="number",
            field=models.BigIntegerField(unique=True),
        ),
    ]
