# Generated by Django 4.2 on 2024-01-29 18:47

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gym_management", "0006_alter_individualevent_training_date"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="club",
            field=models.CharField(max_length=150),
        ),
    ]
