# Generated by Django 4.2 on 2024-01-22 17:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gym_management", "0008_remove_subscription_end_date_subscription_duration"),
    ]

    operations = [
        migrations.AddConstraint(
            model_name="individualevent",
            constraint=models.UniqueConstraint(
                fields=("coach", "participant"), name="unique_coach_participant"
            ),
        ),
    ]
