# Generated by Django 4.2 on 2024-02-07 11:29

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gym_management", "0008_alter_event_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="tags",
            field=models.ManyToManyField(
                blank=True, null=True, to="gym_management.tag"
            ),
        ),
    ]
