# Generated by Django 4.2 on 2024-01-23 09:22

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gym_management", "0009_individualevent_unique_coach_participant"),
    ]

    operations = [
        migrations.AddField(
            model_name="individualevent",
            name="price",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
