# Generated by Django 4.2 on 2024-01-23 09:31

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gym_management", "0010_individualevent_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="individualevent",
            name="description",
            field=models.TextField(default="Personal training"),
        ),
    ]
