# Generated by Django 4.2 on 2024-01-23 09:37

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gym_management", "0011_alter_individualevent_description"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="individualevent",
            name="end_datetime",
        ),
        migrations.AddField(
            model_name="individualevent",
            name="quantity",
            field=models.IntegerField(default=1),
        ),
    ]
