# Generated by Django 4.2 on 2024-02-11 04:45

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gym_management", "0012_alter_event_tags"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="tags",
            field=models.ManyToManyField(default="", to="gym_management.tag"),
        ),
    ]
