# Generated by Django 4.2 on 2024-01-23 09:42

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gym_management", "0012_remove_individualevent_end_datetime_and_more"),
    ]

    operations = [
        migrations.RenameField(
            model_name="individualevent",
            old_name="start_datetime",
            new_name="start_date",
        ),
    ]
