# Generated by Django 4.2 on 2024-01-23 10:25

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gym_management", "0013_rename_start_datetime_individualevent_start_date"),
    ]

    operations = [
        migrations.RenameField(
            model_name="event",
            old_name="start_at",
            new_name="start_date",
        ),
        migrations.AddField(
            model_name="event",
            name="price",
            field=models.PositiveBigIntegerField(default=0),
        ),
    ]
