# Generated by Django 4.2 on 2024-02-16 04:47

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("gym_management", "0014_alter_event_tags"),
    ]

    operations = [
        migrations.RemoveConstraint(
            model_name="individualevent",
            name="unique_coach_participant",
        ),
    ]
