# Generated by Django 4.2 on 2024-01-23 12:15

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gym_management", "0014_rename_start_at_event_start_date_event_price"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="start_date",
            field=models.DateTimeField(),
        ),
        migrations.AlterField(
            model_name="subscription",
            name="duration",
            field=models.IntegerField(),
        ),
    ]
