# Generated by Django 4.2 on 2024-02-19 09:03

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("gym_management", "0015_remove_individualevent_unique_coach_participant"),
    ]

    operations = [
        migrations.AlterField(
            model_name="event",
            name="status",
            field=models.CharField(
                choices=[
                    ("waiting", "Waiting"),
                    ("canceled", "Canceled"),
                    ("passed", "Passed"),
                    ("edit", "Edit"),
                ],
                default="waiting",
                max_length=20,
            ),
        ),
    ]
