# Generated by Django 4.2 on 2024-02-11 07:06

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="agent",
        ),
    ]
