# Generated by Django 4.2 on 2024-02-06 13:45

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0001_initial"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="room",
            name="url",
        ),
    ]
