# Generated by Django 4.2 on 2024-02-11 08:08

from django.db import migrations, models


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0002_remove_room_agent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={"verbose_name": "чат", "verbose_name_plural": "Чаты"},
        ),
        migrations.AlterField(
            model_name="room",
            name="status",
            field=models.CharField(
                choices=[("waiting", "Waiting"), ("active", "Active")],
                default="waiting",
                max_length=20,
            ),
        ),
    ]
