# Generated by Django 4.2 on 2024-02-13 09:36

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0003_alter_room_options_alter_room_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="message",
            options={"verbose_name": "сообщение", "verbose_name_plural": "Сообщения"},
        ),
    ]
