# Generated by Django 4.2 on 2024-02-11 06:46

from django.db import migrations


class Migration(migrations.Migration):
    dependencies = [
        ("chats", "0005_alter_room_agent"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="room",
            options={
                "ordering": ("-created_at",),
                "verbose_name": "чат",
                "verbose_name_plural": "Чаты",
            },
        ),
        migrations.RemoveField(
            model_name="message",
            name="created_by",
        ),
    ]
